# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native/scripts/react_native_pods'

def rn_libs
  # Packages pods
end

target 'Covis' do
  # React native pods
  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])

  # Pods for Covis
  rn_libs

  target 'CovisTests' do
    inherit! :search_paths
    # Pods for testing
  end

  use_native_modules!
end